In [1]:
library(Seurat)
library(Signac)
library(GenomeInfoDb)
library(EnsDb.Hsapiens.v86)
library(ggplot2)
library(patchwork)
library(hdf5r)
library(future)
library(RColorBrewer)
library(dplyr)
library(Matrix)
library(BSgenome.Hsapiens.UCSC.hg38)
library(glue)
library(harmony)
library(matrixStats)
library(scales)
library(biomaRt)
library(curl)
library(goseq)
library(httr)
library(Scillus)
library(TFBSTools)
library(JASPAR2020)
library(ggridges)
library(ggrepel)
library(ggsignif)
library(qusage)
library(tidyverse)
library(effsize)
library(DESeq2)
httr::set_config(config(ssl_verifypeer = 0L))
set.seed(1234)
setwd("/home/jupyter/scATAC_analysis/edit/snatac-rcc-manuscript")
source("scripts/functions.r")

Attaching SeuratObject

Loading required package: BiocGenerics


Attaching package: ‘BiocGenerics’


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, aperm, append, as.data.frame, basename, cbind,
    colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,
    get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply,
    match, mget, order, paste, pmax, pmax.int, pmin, pmin.int,
    Position, rank, rbind, Reduce, rownames, sapply, setdiff, sort,
    table, tapply, union, unique, unsplit, which.max, which.min


Loading required package: S4Vectors

Loading required package: stats4


Attaching package: ‘S4Vectors’


The following object is masked from ‘package:utils’:

    findMatches


The following objects are masked from ‘package:base’:

    expand.grid, I, unname


Loading required package: IRanges

Loading required package: ensembldb

Loading required package: GenomicRanges

Loading required package: GenomicFeatures

Loading required package: AnnotationDbi

Loading required package: Biobase

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.


Loading required package: AnnotationFilter


Attaching package: 'ensembldb'


The following object is masked from 'package:stats':

    filter



Attaching package: 'hdf5r'


The following object is masked from 'package:GenomicRanges':

    values


The following object is masked from 'package:S4Vectors':

    values



Attaching package: 'future'


The following object is masked from 'package:AnnotationFilter':

    value



Attaching package: 'dplyr'


The following objects are masked from 'package:ensembldb':

    filter, select


The following object is masked from 'package:AnnotationDbi':

    select


The following object is masked from 'package:Biobase':

    combine


The following objects are masked from 'package:GenomicRanges':

    intersect, setdiff, union


The following object is masked from 'package:GenomeInfoDb':

    intersect


The following objects are masked from 'package:IRanges':

    collapse, desc, intersect, setdiff, slice, union


The following objects are masked from 'package:S4Vectors':

    first, intersect, rename, setdiff, setequal, union


The following objects are masked from 'package:BiocGenerics':

    combine, intersect, setdiff, union


The following objects are masked from 'package:stats':

    filter, lag


The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union



Attaching package: 'Matrix'


The following object is masked from 'package:S4Vectors':

    expand


Loading required package: BSgenome

Loading required package: Biostrings

Loading required package: XVector


Attaching package: 'Biostrings'


The following object is masked from 'package:base':

    strsplit


Loading required package: BiocIO

Loading required package: rtracklayer


Attaching package: 'rtracklayer'


The following object is masked from 'package:BiocIO':

    FileForFormat



Attaching package: 'glue'


The following object is masked from 'package:GenomicRanges':

    trim


The following object is masked from 'package:IRanges':

    trim


Loading required package: Rcpp


Attaching package: 'matrixStats'


The following object is masked from 'package:dplyr':

    count


The following objects are masked from 'package:Biobase':

    anyMissing, rowMedians


Using libcurl 7.68.0 with GnuTLS/3.6.13

Loading required package: BiasedUrn

Loading required package: geneLenDataBase


Attaching package: 'geneLenDataBase'


The following object is masked from 'package:S4Vectors':

    unfactor





Attaching package: 'httr'


The following object is masked from 'package:curl':

    handle_reset


The following object is masked from 'package:Biobase':

    content



Attaching package: 'TFBSTools'


The following object is masked from 'package:Matrix':

    Matrix


Loading required package: limma


Attaching package: 'limma'


The following object is masked from 'package:BiocGenerics':

    plotMA


── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ lubridate 1.9.4     ✔ tibble    3.3.0
✔ purrr     1.1.0     ✔ tidyr     1.3.1
✔ readr     2.1.5
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ lubridate::%within%()  masks IRanges::%within%()
✖ readr::col_factor()    masks scales::col_factor()
✖ Biostrings::collapse() masks dplyr::collapse(), IRanges::collapse()
✖ dplyr::combine()       masks Biobase::combine(), BiocGenerics::combine()
✖ purrr::compact()       masks XVector::compact()
✖ httr::content()        masks Biobase::content()
✖ matrixStats::count()   masks dplyr::count()
✖ dplyr::desc()          masks IRanges::desc()
✖ purrr::discard()       masks scales::discard()
✖ tidyr::expand()        masks Matrix::expand(), S4Vectors::expand()
✖ dplyr::filter()        masks ensembldb::filter(), stats::filter()
✖ dplyr::first()         masks S4Vectors::first()
✖ purrr::flatten_df()    masks hdf5r::flatten_df()
✖ httr::handle_reset()   masks curl::handle_reset()
✖ dplyr::lag()           masks stats::lag()
✖ tidyr::pack()          masks Matrix::pack()
✖ readr::parse_date()    masks curl::parse_date()
✖ ggplot2::Position()    masks BiocGenerics::Position(), base::Position()
✖ purrr::reduce()        masks GenomicRanges::reduce(), IRanges::reduce(), Signac::reduce()
✖ dplyr::rename()        masks S4Vectors::rename()
✖ lubridate::second()    masks S4Vectors::second()
✖ lubridate::second<-()  masks S4Vectors::second<-()
✖ biomaRt::select()      masks dplyr::select(), ensembldb::select(), AnnotationDbi::select()
✖ XVector::slice()       masks dplyr::slice(), IRanges::slice()
✖ tidyr::unpack()        masks Matrix::unpack()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
Loading required package: SummarizedExperiment

Loading required package: MatrixGenerics


Attaching package: 'MatrixGenerics'


The following objects are masked from 'package:matrixStats':

    colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse,
    colCounts, colCummaxs, colCummins, colCumprods, colCumsums,
    colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs,
    colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats,
    colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds,
    colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads,
    colWeightedMeans, colWeightedMedians, colWeightedSds,
    colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet,
    rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods,
    rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps,
    rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins,
    rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks,
    rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars,
    rowWeightedMads, rowWeightedMeans, rowWeightedMedians,
    rowWeightedSds, rowWeightedVars


The following object is masked from 'package:Biobase':

    rowMedians



Attaching package: 'SummarizedExperiment'


The following object is masked from 'package:SeuratObject':

    Assays


The following object is masked from 'package:Seurat':

    Assays

# Table S3

## Sheet A: DAPs between BAP1 mut tumor cells and BAP1 wt tumor cells, adv stage only

Regions significantly associated with BAP1 mutations status, no log FC filtering.

In [ ]:
markers <- readRDS("processed_data/advstage_tumor_bap1_DAPs.rds")
filtered_markers <- markers %>% filter((p_val_adj < 0.05))
# total pos and neg asssoc peaks
dim(filtered_markers)
filtered_markers$group <- ifelse(filtered_markers$avg_log2FC < 0, "BAP1 WT", "BAP1 pLOF")
filtered_markers[, "row.names"] <- NULL


write.table(filtered_markers, file = "tables/s3a_bap1_ccrcc_diffpeaks.txt", sep = "\t", quote = F, col.names = T, row.names = F)

[1] 13571     7

## Sheet B: DAPs between BAP1 mut tumor cells and BAP1 wt tumor cells, all stages

In [4]:
all_stage_markers <- readRDS("processed_data/allstage_tumor_bap1_DAPs.rds")

all_stage_markers <- all_stage_markers %>% filter((p_val_adj < 0.05))
# total pos and neg asssoc peaks
dim(all_stage_markers)
all_stage_markers$group <- ifelse(all_stage_markers$avg_log2FC < 0, "BAP1 WT", "BAP1 pLOF")
all_stage_markers[, "row.names"] <- NULL


write.table(all_stage_markers, file = "tables/s3b_bap1_ccrcc_diffpeaks_allstages.txt", sep = "\t", quote = F, col.names = T, row.names = F)
head(all_stage_markers)

[1] 16560     6

  p_val avg_log2FC pct.1 pct.2 p_val_adj gene                     group
1 0     -3.005541  0.058 0.219 0         chr1-633720-634509       BAP1 WT
2 0      4.323645  0.212 0.010 0         chr1-5296725-5298329     BAP1 pLOF
3 0      1.792190  0.170 0.046 0         chr1-16623829-16624466   BAP1 pLOF
4 0      2.051107  0.196 0.042 0         chr1-55442584-55444168   BAP1 pLOF
5 0      1.767395  0.271 0.073 0         chr1-109820986-109822694 BAP1 pLOF
6 0      2.746937  0.178 0.023 0         chr1-167697175-167698570 BAP1 pLOF

## Sheet C: Enriched pathways in BAP1 mutation associated peak set using GREAT

In [10]:
great_results <- readRDS("processed_data/BAP1_tumor_DAP_GREAT_pathway_results.rds")
great_results

    Ontology              ID
1   GO Biological Process GO:0060337
2   GO Biological Process GO:0071357
3   GO Biological Process GO:0034340
4   GO Biological Process GO:0003104
5   GO Biological Process GO:0002335
6   GO Biological Process GO:0003093
7   GO Biological Process GO:0035455
8   GO Biological Process GO:0044387
9   GO Biological Process GO:0060333
10  GO Biological Process GO:2000514
11  GO Biological Process GO:0061098
12  GO Biological Process GO:0001977
13  GO Biological Process GO:0006382
14  GO Biological Process GO:0002313
15  GO Biological Process GO:0060266
16  GO Biological Process GO:0032653
17  GO Biological Process GO:0097241
18  GO Biological Process GO:2000532
19  GO Biological Process GO:2000669
20  GO Biological Process GO:0060644
21  GO Biological Process GO:0060264
22  GO Biological Process GO:0032571
23  GO Biological Process GO:0019064
24  GO Biological Process GO:1902107
25  GO Biological Process GO:2000516
26  GO Biological Process GO:0043370
27  GO Biological Process GO:2000510
28  GO Biological Process GO:0045619
29  GO Biological Process GO:0016556
30  GO Biological Process GO:0043903
⋮   ⋮                     ⋮
105 GO Biological Process GO:0048247
106 GO Biological Process GO:0043407
107 GO Biological Process GO:0043467
108 GO Biological Process GO:0043901
109 GO Biological Process GO:0002285
110 GO Biological Process GO:0010804
111 GO Biological Process GO:0031669
112 GO Biological Process GO:0002819
113 GO Biological Process GO:0032735
114 GO Biological Process GO:0050873
115 GO Biological Process GO:0030853
116 GO Biological Process GO:0002931
117 GO Biological Process GO:0050764
118 GO Biological Process GO:0043491
119 GO Biological Process GO:0032713
120 GO Biological Process GO:0072007
121 GO Biological Process GO:0072661
122 GO Biological Process GO:0008542
123 GO Biological Process GO:0046637
124 GO Biological Process GO:0048524
125 GO Biological Process GO:0010906
126 GO Biological Process GO:0043508
127 GO Biological Process GO:0001997
128 GO Biological Process GO:2000171
129 GO Biological Process GO:2000269
130 GO Biological Process GO:0071731
131 GO Biological Process GO:0001766
132 GO Biological Process GO:0090324
133 GO Biological Process GO:0050951
134 GO Biological Process GO:0003057
    Desc
1   type I interferon-mediated signaling pathway
2   cellular response to type I interferon
3   response to type I interferon
4   positive regulation of glomerular filtration
5   mature B cell differentiation
6   regulation of glomerular filtration
7   response to interferon-alpha
8   negative regulation of protein kinase activity by regulation of protein phosphorylation
9   interferon-gamma-mediated signaling pathway
10  regulation of CD4-positive, alpha-beta T cell activation
11  positive regulation of protein tyrosine kinase activity
12  renal system process involved in regulation of blood volume
13  adenosine to inosine editing
14  mature B cell differentiation involved in immune response
15  negative regulation of respiratory burst involved in inflammatory response
16  regulation of interleukin-10 production
17  hematopoietic stem cell migration to bone marrow
18  regulation of renal albumin absorption
19  negative regulation of dendritic cell apoptotic process
20  mammary gland epithelial cell differentiation
21  regulation of respiratory burst involved in inflammatory response
22  response to vitamin K
23  fusion of virus membrane with host plasma membrane
24  positive regulation of leukocyte differentiation
25  positive regulation of CD4-positive, alpha-beta T cell activation
26  regulation of CD4-positive, alpha-beta T cell differentiation
27  positive regulation of dendritic cell chemotaxis
28  regulation of lymphocyte differentiation
29  mRNA modification
30  regulation of symbiosis, encompassing mutualism through parasitism
⋮   ⋮
105 lymphocyte chemotaxis
106 negative regulation of MAP kinase activity
107 regulation of generation of precursor metabolites and energy
108 negative regulation of multi-organism process
109 lymphocyte activation involved in immune response
110 negative regulation of tumor necrosis factor-mediated signaling pathway
111 cellular response to nutrient levels
112 regulation of adaptive immune response
113 positive regulation of interleukin-12 production
114 brown fat cell differentiation
115 negative regulation of granulocyte differentiation
116 response to ischemia
117 regulation of phagocytosis
118 protein kinase B signaling cascade
119 negative regulation of interleukin-4 production
120 mesangial cell differentiation
121 protein targeting to plasma membrane
122 visual learning
123 regulation of alpha-beta T cell differentiation
124 positive regulation of viral process
125 regulation of glucose metabolic process
126 negative regulation of JUN kinase activity
127 positive regulation of the force of heart contraction by epinephrine-norepinephrine
128 negative regulation of dendrite development
129 regulation of fibroblast apoptotic process
130 response to nitric oxide
131 membrane raft polarization
132 negative regulation of oxidative phosphorylation
133 sensory perception of temperature stimulus
134 regulation of the force of heart contraction by chemical signal
    BinomRank BinomP       BinomBonfP   BinomFdrQ    RegionFoldEnrich
1    2        1.506053e-08 0.0001572319 7.861597e-05  5.116779
2    3        1.523016e-08 0.0001590029 5.300096e-05  5.113094
3    4        1.836392e-08 0.0001917193 4.792983e-05  5.051852
4    5        1.959790e-08 0.0002046021 4.092042e-05 25.193980
5    8        3.740177e-08 0.0003904745 4.880931e-05 11.231350
6    9        6.362473e-08 0.0006642422 7.380469e-05 12.714270
7   12        1.581293e-07 0.0016508700 1.375725e-04  8.310803
8   13        1.656943e-07 0.0017298480 1.330653e-04 18.334410
9   15        3.547965e-07 0.0037040750 2.469384e-04  3.666618
10  16        5.186854e-07 0.0054150760 3.384422e-04  4.048851
11  24        8.322362e-07 0.0086885460 3.620227e-04  4.109343
12  25        9.254356e-07 0.0096615480 3.864619e-04  9.193890
13  26        9.400855e-07 0.0098144930 3.774805e-04 14.106920
14  28        9.931752e-07 0.0103687500 3.703125e-04 11.012310
15  31        1.419426e-06 0.0148188100 4.780260e-04 10.489910
16  33        1.529964e-06 0.0159728200 4.840250e-04  4.135155
17  36        1.719115e-06 0.0179475600 4.985433e-04 26.410190
18  38        2.222048e-06 0.0231981800 6.104785e-04 25.046200
19  41        2.577490e-06 0.0269090000 6.563170e-04 24.288830
20  42        2.656132e-06 0.0277300200 6.602385e-04  4.183798
21  43        2.758454e-06 0.0287982600 6.697270e-04  9.577435
22  45        4.348151e-06 0.0453947000 1.008771e-03 21.791790
23  46        4.601150e-06 0.0480360100 1.044261e-03 21.537040
24  47        4.658331e-06 0.0486329800 1.034744e-03  2.301256
25  49        5.491795e-06 0.0573343400 1.170089e-03  4.453707
26  51        5.840301e-06 0.0609727400 1.195544e-03  3.925757
27  52        6.373455e-06 0.0665388700 1.279594e-03 20.124070
28  53        8.165192e-06 0.0852446000 1.608389e-03  2.303389
29  54        8.855647e-06 0.0924529500 1.712092e-03  9.984141
30  55        9.008116e-06 0.0940447300 1.709904e-03  2.481233
⋮   ⋮         ⋮            ⋮            ⋮            ⋮
105 207       0.0005827091 1            0.02938881    4.409939
106 210       0.0006117107 1            0.03041076    2.213601
107 211       0.0006151148 1            0.03043506    2.377000
108 213       0.0006471822 1            0.03172104    2.597015
109 214       0.0006481976 1            0.03162235    2.433710
110 215       0.0006539077 1            0.03175254    7.434474
111 216       0.0006553386 1            0.03167470    2.080275
112 217       0.0006554214 1            0.03153272    2.046214
113 221       0.0006824886 1            0.03224064    2.933830
114 224       0.0007068266 1            0.03294317    3.084360
115 225       0.0007126959 1            0.03306909    5.782606
116 226       0.0007180723 1            0.03317113    7.279561
117 227       0.0007266669 1            0.03342028    2.779367
118 228       0.0007339813 1            0.03360862    3.267019
119 230       0.0007694212 1            0.03492503    5.696847
120 233       0.0007946264 1            0.03560472    5.661070
121 234       0.0007964456 1            0.03553373    3.784802
122 237       0.0008505430 1            0.03746696    2.529247
123 239       0.0008805875 1            0.03846583    2.439281
124 240       0.0009382698 1            0.04081474    2.597449
125 241       0.0009569828 1            0.04145602    2.023690
126 242       0.0009664208 1            0.04169187    4.073247
127 243       0.0010048330 1            0.04317060    6.746451
128 247       0.0010505920 1            0.04440559    4.556527
129 248       0.0010683980 1            0.04497611    3.626643
130 251       0.0011035310 1            0.04589986    6.603979
131 253       0.0011405020 1            0.04706261    8.995068
132 255       0.0011840040 1            0.04847452   14.830110
133 256       0.0011908700 1            0.04856517    3.939991
134 259       0.0012225890 1            0.04928119    5.200378
    ExpRegions ObsRegions ⋯ HyperRank HyperP       HyperBonfP HyperFdrQ
1    3.7132740 19         ⋯ 1782      1.212223e-01 1.0000000  0.710191300
2    3.7159490 19         ⋯ 1875      1.300918e-01 1.0000000  0.724351100
3    3.7609970 19         ⋯ 1911      1.392929e-01 1.0000000  0.760972200
4    0.2778442  7         ⋯  702      2.305766e-02 1.0000000  0.342908800
5    0.8903649 10         ⋯ 1068      5.468656e-02 1.0000000  0.534576500
6    0.7078661  9         ⋯  918      4.097267e-02 1.0000000  0.465963700
7    1.3235790 11         ⋯ 2439      1.946947e-01 1.0000000  0.833379500
8    0.3817958  7         ⋯  961      4.335949e-02 1.0000000  0.471043800
9    6.0000800 22         ⋯  314      2.752287e-03 1.0000000  0.091509160
10   4.6926890 19         ⋯  384      5.241758e-03 1.0000000  0.142510300
11   4.3802620 18         ⋯  119      7.142235e-05 0.7456493  0.006265961
12   0.9789110  9         ⋯ 1849      1.268862e-01 1.0000000  0.716437000
13   0.4962102  7         ⋯  702      2.305766e-02 1.0000000  0.342908800
14   0.7264598  8         ⋯ 1987      1.589701e-01 1.0000000  0.835253100
15   0.7626374  8         ⋯ 2666      2.475852e-01 1.0000000  0.969538400
16   4.1110910 17         ⋯  587      1.556852e-02 1.0000000  0.276891600
17   0.1893208  5         ⋯ 2088      1.727427e-01 1.0000000  0.863713500
18   0.1996311  5         ⋯ 2088      1.727427e-01 1.0000000  0.863713500
19   0.2058560  5         ⋯ 2666      2.475852e-01 1.0000000  0.969538400
20   3.8242760 16         ⋯  278      1.959975e-03 1.0000000  0.073604820
21   0.8352967  8         ⋯ 3116      3.156604e-01 1.0000000  1.000000000
22   0.2294442  5         ⋯ 2666      2.475852e-01 1.0000000  0.969538400
23   0.2321582  5         ⋯ 3116      3.156604e-01 1.0000000  1.000000000
24  16.0781700 37         ⋯  764      2.439938e-02 1.0000000  0.333415600
25   3.1434490 14         ⋯  755      2.387940e-02 1.0000000  0.330199900
26   4.0756470 16         ⋯  947      4.225911e-02 1.0000000  0.465876600
27   0.2484587  5         ⋯ 3497      3.775799e-01 1.0000000  1.000000000
28  15.1950000 35         ⋯  578      1.503146e-02 1.0000000  0.271502500
29   0.7011119  7         ⋯ 1987      1.589701e-01 1.0000000  0.835253100
30  12.0907600 30         ⋯ 1736      1.071952e-01 1.0000000  0.644653200
⋮   ⋮          ⋮          ⋱ ⋮         ⋮            ⋮          ⋮
105  1.8140840  8         ⋯ 1849      0.126886200  1          0.7164370
106  9.9385560 22         ⋯ 1253      0.071818120  1          0.5983888
107  7.9932670 19         ⋯  612      0.017583550  1          0.2999547
108  6.1609180 16         ⋯ 1869      0.129205300  1          0.7217246
109  7.3961160 18         ⋯ 1216      0.068852880  1          0.5911382
110  0.6725425  5         ⋯ 4093      0.485126800  1          1.0000000
111 12.0176400 25         ⋯ 1784      0.123322500  1          0.7216855
112 12.7063900 26         ⋯  752      0.023441340  1          0.3254356
113  4.4310670 13         ⋯  362      0.004267232  1          0.1230660
114  3.8905960 12         ⋯  587      0.015568520  1          0.2768916
115  1.0375950  6         ⋯  655      0.019579480  1          0.3120760
116  0.6868546  5         ⋯ 1793      0.126539300  1          0.7367932
117  5.0371180 14         ⋯ 1303      0.080757910  1          0.6470549
118  3.3669840 11         ⋯ 1764      0.116129900  1          0.6872994
119  1.0532140  6         ⋯ 3497      0.377579900  1          1.0000000
120  1.0598700  6         ⋯  536      0.011988400  1          0.2335054
121  2.3779320  9         ⋯ 1129      0.061202560  1          0.5659475
122  6.3259930 16         ⋯ 2034      0.161901700  1          0.8309999
123  6.9692670 17         ⋯ 1303      0.080757910  1          0.6470549
124  5.7748970 15         ⋯ 3310      0.325414700  1          1.0000000
125 12.3536700 25         ⋯  693      0.021786870  1          0.3282178
126  1.9640350  8         ⋯ 5034      0.679594500  1          1.0000000
127  0.7411304  5         ⋯  702      0.023057660  1          0.3429088
128  1.5362580  7         ⋯  961      0.043359490  1          0.4710438
129  2.4816340  9         ⋯  918      0.040972670  1          0.4659637
130  0.7571193  5         ⋯ 4551      0.574100300  1          1.0000000
131  0.4446881  4         ⋯  702      0.023057660  1          0.3429088
132  0.2022911  3         ⋯ 2088      0.172742700  1          0.8637135
133  2.0304610  8         ⋯  407      0.006010132  1          0.1541665
134  1.1537620  6         ⋯  655      0.019579480  1          0.3120760
    GeneFoldEnrich ExpGenes   ObsGenes TotalGenes GeneSetCov   TermCov
1   1.554544        5.7894800  9        64        0.0055147060 0.1406250
2   1.530628        5.8799400  9        65        0.0055147060 0.1384615
3   1.507436        5.9704010  9        66        0.0055147060 0.1363636
4   7.369690        0.2713819  2         3        0.0012254900 0.6666667
5   3.316360        0.9046062  3        10        0.0018382350 0.3000000
6   3.684845        0.8141456  3         9        0.0018382350 0.3333333
7   1.950800        1.5378300  3        17        0.0018382350 0.1764706
8   5.527267        0.3618425  2         4        0.0012254900 0.5000000
9   2.355884        5.5180980 13        61        0.0079656860 0.2131148
10  2.852783        2.8042790  8        31        0.0049019610 0.2580645
11  4.094272        2.4424370 10        27        0.0061274510 0.3703704
12  2.368829        1.2664490  3        14        0.0018382350 0.2142857
13  7.369690        0.2713819  2         3        0.0012254900 0.6666667
14  2.763634        0.7236849  2         8        0.0012254900 0.2500000
15  3.684845        0.2713819  1         3        0.0006127451 0.3333333
16  2.579391        2.7138190  7        30        0.0042892160 0.2333333
17  5.527267        0.1809212  1         2        0.0006127451 0.5000000
18  5.527267        0.1809212  1         2        0.0006127451 0.5000000
19  3.684845        0.2713819  1         3        0.0006127451 0.3333333
20  4.145450        1.4473700  6        16        0.0036764710 0.3750000
21  2.763634        0.3618425  1         4        0.0006127451 0.2500000
22  3.684845        0.2713819  1         3        0.0006127451 0.3333333
23  2.763634        0.3618425  1         4        0.0006127451 0.2500000
24  1.700698        9.4079040 16       104        0.0098039220 0.1538462
25  2.909088        1.7187520  5        19        0.0030637250 0.2631579
26  2.287145        2.6233580  6        29        0.0036764710 0.2068966
27  2.210907        0.4523031  1         5        0.0006127451 0.2000000
28  1.730275       10.4029700 18       115        0.0110294100 0.1565217
29  2.763634        0.7236849  2         8        0.0012254900 0.2500000
30  1.381817       12.3026400 17       136        0.0104166700 0.1250000
⋮   ⋮              ⋮          ⋮        ⋮          ⋮            ⋮
105 2.3688290       1.2664490  3        14        0.0018382350 0.21428570
106 1.6749290       5.9704010 10        66        0.0061274510 0.15151520
107 2.0266650       5.4276370 11        60        0.0067401960 0.18333330
108 1.4938560       6.6940860 10        74        0.0061274510 0.13513510
109 1.7454530       5.1562550  9        57        0.0055147060 0.15789470
110 1.5792190       0.6332243  1         7        0.0006127451 0.14285710
111 1.4228610       9.1365220 13       101        0.0079656860 0.12871290
112 1.6779200      10.1315900 17       112        0.0104166700 0.15178570
113 3.2242390       2.1710550  7        24        0.0042892160 0.29166670
114 2.5793910       2.7138190  7        30        0.0042892160 0.23333330
115 4.7376580       0.6332243  3         7        0.0018382350 0.42857140
116 3.1584380       0.6332243  2         7        0.0012254900 0.28571430
117 1.8424220       3.7993460  7        42        0.0042892160 0.16666670
118 1.9059540       2.6233580  5        29        0.0030637250 0.17241380
119 2.2109070       0.4523031  1         5        0.0006127451 0.20000000
120 5.5272670       0.5427637  3         6        0.0018382350 0.50000000
121 2.6010670       1.5378300  4        17        0.0024509800 0.23529410
122 1.6177370       3.7088850  6        41        0.0036764710 0.14634150
123 1.8424220       3.7993460  7        42        0.0042892160 0.16666670
124 1.2282820       6.5131640  8        72        0.0049019610 0.11111110
125 1.7995750       7.7796130 14        86        0.0085784310 0.16279070
126 0.9212112       1.0855270  1        12        0.0006127451 0.08333333
127 7.3696900       0.2713819  2         3        0.0012254900 0.66666670
128 5.5272670       0.3618425  2         4        0.0012254900 0.50000000
129 3.6848450       0.8141456  3         9        0.0018382350 0.33333330
130 1.2282820       0.8141456  1         9        0.0006127451 0.11111110
131 7.3696900       0.2713819  2         3        0.0012254900 0.66666670
132 5.5272670       0.1809212  1         2        0.0006127451 0.50000000
133 3.9480480       1.2664490  5        14        0.0030637250 0.35714290
134 4.7376580       0.6332243  3         7        0.0018382350 0.42857140

In [11]:
write.table(great_results, "tables/s3c_BAP1_pLOF_GREAT_GOBP_output.txt", sep = "\t", quote = F, row.names = F, col.names = T)

## Sheet D: TF binding site motif enrichment in BAP1 mutation associated peaks

In [8]:
enriched_motifs = readRDS("processed_data/BAP1_tfmotifs.rds")

write.table(enriched_motifs %>% filter(p.adjust < 0.05),
    file = "tables/s3d_BAP1_tfmotifs.txt", sep = "\t", quote = F, row.names = F, col.names = T
)

## Sheet E: GSEA of RNA-seq data from BAP1 knockout vs wild type 786O cells

In [16]:
gsea = readRDS('processed_data/gsea_bap1ko_wt_7860_rna.rds')
write.table(gsea, file = 'tables/s3e_7686o_rna_gsea.txt', sep = '\t', quote = F, row.names = F, col.names = T)

## Sheet F: ORA of DEPs from BAP1 KO vs WT 786-O cells

In [9]:
ora_all = readRDS('processed_data/ora_bap1ko_wt_7860_protein.rds')
ora_supp <- ora_all %>% dplyr::select(-c(ID, log10padj, geneRatio_raw, geneRatio))
write.table(ora_supp, "tables/s3f_ora_bap1ko_wt_7860_protein.txt", sep = "\t", quote = F, row.names = F, col.names = T)

# Export to Excel

In [1]:
import pandas as pd
import os
os.chdir('/home/jupyter/scATAC_analysis/edit/snatac-rcc-manuscript')

In [5]:
bap1_daps = pd.read_csv("tables/s3a_bap1_ccrcc_diffpeaks.txt", sep = "\t")
bap1_daps.head()

bap1_daps_allstage = pd.read_csv("tables/s3b_bap1_ccrcc_diffpeaks_allstages.txt", sep = "\t")
bap1_daps_allstage.head()

bap1_plof_pathways = pd.read_csv("tables/s3c_BAP1_pLOF_GREAT_GOBP_output.txt", sep = "\t")
bap1_plof_pathways.head()

bap1_plof_tf_motifs = pd.read_csv("tables/s3d_BAP1_tfmotifs.txt", sep = "\t")
bap1_plof_tf_motifs.head()

gsea = pd.read_csv("tables/s3e_7686o_rna_gsea.txt", sep = "\t")
gsea = gsea.loc[gsea['pathway'] != 'type-I inducible tumor']
gsea.loc[gsea['pathway'] == '(Bi et al)', 'pathway'] = 'type-I inducible tumor (Bi et al)'
gsea.head()

ora = pd.read_csv("tables/s3f_ora_bap1ko_wt_7860_protein.txt", sep = "\t")
ora = ora.loc[ora['Description'] != 'type-I inducible tumor']
ora.loc[ora['Description'] == '(Bi et al)', 'Description'] = 'type-I inducible tumor (Bi et al)'
ora.head()

,Description,GeneRatio,BgRatio,pvalue,p.adjust,qvalue,geneID,Count,Direction
0,INTERFERON_ALPHA_RESPONSE,27/312,61/2390,1.127301e-09,5.749236e-08,4.746531e-08,IFI44/HLA-C/HERC6/OASL/SP110/DDX60/NMI/EIF2AK2...,27.0,KO
1,INTERFERON_GAMMA_RESPONSE,34/312,98/2390,1.629177e-08,2.923842e-07,2.413904e-07,IFI44/HERC6/OASL/SP110/TNFAIP2/OAS3/DDX60/NMI/...,34.0,KO
3,type-I inducible tumor (Bi et al),29/312,76/2390,1.719907e-08,2.923842e-07,2.413904e-07,IFI44/HLA-C/HERC6/OASL/SP110/DDX58/OAS3/DDX60/...,29.0,KO
4,FATTY_ACID_METABOLISM,29/312,108/2390,6.426785e-05,8.194151e-04,6.765037e-04,IL4I1/ECH1/MDH1/EHHADH/SUCLA2/CA2/ACO2/HADHB/S...,29.0,KO
5,ESTROGEN_RESPONSE_LATE,22/312,84/2390,7.382326e-04,7.529973e-03,6.216696e-03,FARP1/IDH2/ETFB/CCND1/IMPA2/WFS1/DNAJC1/CA2/TP...,22.0,KO

In [6]:
with pd.ExcelWriter('tables/table_S3_draft.xlsx') as writer:  
    bap1_daps.to_excel(writer, sheet_name='A', index = False)
    bap1_daps_allstage.to_excel(writer, sheet_name='B', index = False)
    bap1_plof_pathways.to_excel(writer, sheet_name='C', index = False)
    bap1_plof_tf_motifs.to_excel(writer, sheet_name='D', index = False)
    gsea.to_excel(writer, sheet_name='E', index = False)
    ora.to_excel(writer, sheet_name='F', index = False)